version: '3.3'
services:
  web:
    container_name: booknest-web
    build:
      context: ./
    volumes:
      - .:/src
    command: supervisor -e '.' index.js
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    container_name: booknest-db
    image: mysql
    restart: always
    env_file:
      - ./.env
    ports:
      - "${MYSQL_PORT:-3306}:${DB_PORT}"
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    container_name: booknest-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
    environment:
      PMA_HOST: ${DB_CONTAINER}
      PMA_PORT: ${DB_PORT}
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
